### ISSUE TITLE
How i can get error in twig?

### ISSUE THREAD

**Issue by kolyadin** [vitiko/IphpFileStoreBundle#34]
For example:

{{ form_errors(form.image) }}

does not show any errors, but

{{ form_errors(form) }}

shows errors as well

So, question is: how can i access image errors via {{ form_errors(form.image) }} in twig?

**Comment by LouTerrailloune** [comment]
Add `'error_bubbling' => false` to option of the iphp_file field.

```php
            ->add('picture', 'iphp_file', array(
                'required' => false,
                'label' => 'Photo',
                'error_bubbling' => false,
            ))
```
I don't know why it's true by default.
